name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

premissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-18.04]

    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          vesion: v1.29
